### ISSUE TITLE
You behave badly in developers community 

### ISSUE THREAD

**Issue by excal1bu7** [rachaeldawn/effector-types-bug#1]
Hi. Your github bio is wrong:
![image](https://user-images.githubusercontent.com/57995626/187774315-742cb978-99e8-48cd-b62b-651cd1ec3496.png)
Remove it `If you're a dev who needs help, feel free to reach out to me on Discord. Reference this bio in your greeting Rachael#3022` from you github bio, please

**Comment by rachaeldawn** [comment]
> Hi. Your github bio is wrong:
> 
> ![image](https://user-images.githubusercontent.com/57995626/187774315-742cb978-99e8-48cd-b62b-651cd1ec3496.png)
> 
> Remove it `If you're a dev who needs help, feel free to reach out to me on Discord. Reference this bio in your greeting Rachael#3022` from you github bio, please 

No.
